//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 11:32:29 PM IST 
//


package com.example.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for driver complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="driver">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="driverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driverEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driverLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "driver", propOrder = {
    "driverName",
    "driverEmail",
    "driverLocation"
})
public class Driver {

    @XmlElement(required = true)
    protected String driverName;
    @XmlElement(required = true)
    protected String driverEmail;
    @XmlElement(required = true)
    protected String driverLocation;

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverEmail() {
        return driverEmail;
    }

    /**
     * Sets the value of the driverEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverEmail(String value) {
        this.driverEmail = value;
    }

    /**
     * Gets the value of the driverLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverLocation() {
        return driverLocation;
    }

    /**
     * Sets the value of the driverLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverLocation(String value) {
        this.driverLocation = value;
    }

}
