//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.23 at 11:32:29 PM IST 
//


package com.example.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DriversList }
     * 
     */
    public DriversList createDriversList() {
        return new DriversList();
    }

    /**
     * Create an instance of {@link GetDriversByLocationResponse }
     * 
     */
    public GetDriversByLocationResponse createGetDriversByLocationResponse() {
        return new GetDriversByLocationResponse();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link GetDriversByLocationRequest }
     * 
     */
    public GetDriversByLocationRequest createGetDriversByLocationRequest() {
        return new GetDriversByLocationRequest();
    }

}
